spring:
  application:
    name: elice

  datasource:
    url: jdbc:mysql://elicerds.cfggw8m0anz0.ap-northeast-2.rds.amazonaws.com:3306/elice2
    username: root
    password: passw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
